language: java
sudo: true
dist: trusty

jdk:
- oraclejdk8

cache:
  directories:
  - '$HOME/.m2/repository'

addons:
  firefox: latest
  apt:
    packages:
       - google-chrome-stable

before_install:
  - sudo apt-get -y update
  - sudo apt-get install openssl
  - sudo apt-get install ssmtp
  - sudo apt-get install sasl2-bin
  - sudo apt-get install heirloom-mailx
  - sudo sleep 3
  - sudo echo "This is the message body and contains the message" | mailx -v -r "artem@sokovets.ru" -s "This is the subject123" -S smtp="smtp.timeweb.ru:25" -S smtp-use-starttls -S smtp-auth=login -S smtp-auth-user="artem@sokovets.ru" -S smtp-auth-password="$password" -S ssl-verify=ignore relix@mail.ru
before_script:
  - google-chrome --version #Show Chrome Versions
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - echo
script:
    - mvn clean test
#    - mvn clean test site jetty:run

after_script:
  - echo "Test"

notifications:
  email:
    recipients:
        - relix@mail.ru
    on_success: never
    on_failure: always