language: java
sudo: true
dist: trusty

jdk:
- oraclejdk8

cache:
  directories:
  - '$HOME/.m2/repository'

addons:
  firefox: latest
  apt:
    packages:
       - google-chrome-stable

before_install:
  - sudo apt-get -y update
  - debconf-set-selections <<< "postfix postfix/mailname string $email"
  - debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'"
  - apt-get -y update
  - apt-get install -y mailutils
  - apt-get install -y ssmtp
  - echo -e "FromLineOverride=YES \nAuthUser=$email \nAuthPass=$password \nmailhub=smtp.timeweb.ru:25 \nUseSTARTTLS=YES" >> /etc/ssmtp/ssmtp.conf

before_script:
  - google-chrome --version #Show Chrome Versions
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - echo
script:
    - mvn clean test
#    - mvn clean test site jetty:run

after_script:
  - echo "This is a test" | mail --debug-level 10 -s "Tesasdasdsad" -aFrom:$email $email2

notifications:
  email:
    recipients:
        - relix@mail.ru
    on_success: never
    on_failure: always