language: java
sudo: true
dist: trusty

jdk:
- oraclejdk8

cache:
  directories:
  - '$HOME/.m2/repository'

addons:
  firefox: latest
  apt:
    packages:
       - google-chrome-stable

before_script:
  - google-chrome --version #Show Chrome Versions
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - ifconfig

script:
    - mvn clean test site jetty:run


notifications:
  email:
    recipients:
        - AVSokovets.SBT@sberbank.ru
    on_success: always
    on_failure: never