language: java
sudo: false
dist: trusty

addons:
    sonarcloud:
        organization: "artsok-github"
        token:
            secure: $SONAR_TOKEN

cache:
  directories:
  - '$HOME/.m2/repository'

jdk:
- oraclejdk8

script:
    - mvn test sonar:sonar

deploy:
  - provider: script
    script: ".travis/deploy.sh"
    on:
      repo: artsok/rerunner-jupiter
      branch: master

  - provider: script
    script: ".travis/deploy.sh"
    skip_cleanup: true
    on:
      repo: artsok/rerunner-jupiter
      tags: true